# Generated by Django 5.0.6 on 2024-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Картинка')),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
            ],
        ),
    ]
