# Generated by Django 5.0.6 on 2024-05-18 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tovar_discount_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('zakaz', models.TextField(verbose_name='Заказ')),
                ('status', models.CharField(choices=[(1, 'в сборке'), (2, 'в пути'), (3, 'доставлен')], max_length=100)),
                ('items', models.ManyToManyField(to='app.tovar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
