# Generated by Django 5.0.6 on 2024-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='category',
            field=models.CharField(blank=True, choices=[(1, 'Продукты'), (2, 'Одежда'), (3, 'Для шлолы'), (4, 'Для дома')], max_length=100, null=True),
        ),
    ]
