# Generated by Django 5.0.6 on 2024-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tovar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в сборке', 'в сборке'), ('в пути', 'в пути'), ('доставлен', 'доставлен')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.CharField(blank=True, choices=[('П', 'Продукты'), ('О', 'Одежда'), ('Ш', 'Для шлолы'), ('Д', 'Для дома')], max_length=100, null=True),
        ),
    ]
